run:
  timeout: 5m
linters-settings:
  govet:
    check-shadowing: true
linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - typecheck
    - unconvert
    - unused
    - gosimple
    - ineffassign